
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS_PRICES = 'SET_INGREDIENTS_PRICES';
export const FETCH_INGREDIENTS_PRICES_FAILED = 'FETCH_INGREDIENTS_PRICES_FAILED';
export const FETCH_INGREDIENTS_PRICES_STARTED = 'FETCH_INGREDIENTS_PRICES_STARTED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_STARTED = 'PURCHASE_BURGER_STARTED';
