
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS_PRICES = 'SET_INGREDIENTS_PRICES';
export const FETCH_INGREDIENTS_PRICES_FAILED = 'FETCH_INGREDIENTS_PRICES_FAILED';
export const FETCH_INGREDIENTS_PRICES_EFFECT = 'FETCH_INGREDIENTS_PRICES_EFFECT';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_EFFECT_STARTED = 'PURCHASE_BURGER_EFFECT_STARTED';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_STARTED = 'PURCHASE_BURGER_STARTED';
export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';

export const FETCH_ORDERS_STARTED = 'FETCH_ORDERS_STARTED';
export const FETCH_ORDERS_EFFECT_STARTED = 'FETCH_ORDERS_EFFECT_STARTED';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_EFFECT_STARTED = 'AUTH_EFFECT_STARTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_EFFECT_STARTED = 'AUTH_CHECK_EFFECT_STARTED';
export const AUTH_INITIATED_LOGOUT = 'AUTH_INITIATED_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


